name: postupgrade
version: '0.0.0.0'
description: Read database for Persistent 2.11 deserialization example

dependencies:
- base >= 4.7 && < 5
- bytestring
- persistent
- persistent-postgresql
- persistent-template
- postgresql-simple
- text

executables:
  persistent-serialization-exe:
    main: Main.hs
    source-dirs: src
