name: preupgrade
version: '0.0.0.0'
description: Seed database for Persistent 2.11 deserialization example

dependencies:
- base >= 4.7 && < 5
- bytestring
- persistent >= 2.10 && < 2.11
- persistent-postgresql
- persistent-template
- postgresql-simple
- text

executables:
  persistent-serialization-exe:
    main: Main.hs
    source-dirs: src
